config/routes.rb
Rails.application.routes.draw do
  resources :billboards
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: "registrations" }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # resources :partial_qualifications

  resources :partial_qualifications
  resources :home, only: [:index, :show] do
    collection do
      # get 'select_role'
      get 'longged_in'
    end
  end

  resources :payment_details do
    member do
      get 'confirm'
      get 'read_report'
      get 'generate_pdf'
    end

  end

  resources :instructors, only: [:index] do
    member do
      get 'work_proof'
      get 'work_proof_verify'
    end
  end

  resources :careers, only: [:index] do
    member do
      get 'constance'
      get 'constance_verify'
      get 'career_finished_certificate'
      get 'career_finished_certificate_verify'
    end
  end

  resources :academic_records, only: [:index, :show] do
    member do
      get 'send_confirmation_mail'
      get 'show_payments_accounts'
      get 'certificate'
    end
  end

  resources :sections, only: [:index] do
    member do
      get 'sync_up_with_canvas'
      get 'delete'
      get 'unsplit'
      get 'split'
      get 'enrollments_to_canvas'
      get 'create_on_canvas'
    end
  end

  resources :qualification_schemas, only: [:index] do
    member do
      get 'onoff_switch'
    end
  end

  resources :periods, only: [:index] do
    member do
      get :unreported
      get 'onoff_switch'
      get 'clean_not_reported'
    end
  end

  scope module: :admin do
    resources :dashboard, only: [:index]
  end

  namespace :api do
    namespace :v1 do
      resources :items, only: [:index, :create, :destroy, :update] do 
        collection do
          get 'open_newers_registration'
        end
      end
    end
  end

  resources :student_session, only: [:index] do
    collection do
      get 'multimedia'
    end
  end
  resources :instructor_session, only: [:index] do
    member do
      get 'show_sections'
    end
  end
  resources :enrollment, only: [:index] do
    member do
      get 'regular'
      get 'import_aceim_old'
      get 'sync_up_with_canvas'
    end
  end

  resources :canvas, only: [:index] do
    member do
      get 'sync_with_canvas'
    end
  end

  resources :users, only: [:update] do
    member do
      post 'update_canvas_email'
      get 'registration_canvas'
    end
    collection do
      get 'registration_canvas_all'
    end
  end

  
  root to: 'home#index'
end

app/models/career.rb
class Career < ApplicationRecord

  # =============== ASSOTIACIONS =================#
  belongs_to :agreement, inverse_of: :careers
  belongs_to :language, inverse_of: :careers
  belongs_to :student, inverse_of: :careers
  belongs_to :leveling_period, foreign_key: :leveling_period_id, class_name: 'Period', optional: true#, inverse_of: :carrers
  
  has_one :user, through: :student

  # has_many :academic_records, through: :student 

  # =============== VALIATIONS =================#
  validates :agreement_id, presence: true
  validates :language_id, presence: true
  validates :student_id, presence: true

  
  # =============== SCOPES =================#

  scope :leveled, -> {where('leveling IS NOT NULL')}
  scope :not_leveled, -> {where('leveling IS NULL')}

  # =============== FUNCTIONS =================#
  # def academic_records
  #   self.student.academic_records.joins(:level).order('levels.grade desc').from_language(language_id)
  # end

  def enrollment_leveling
    academic_records.where("levels.id = 'NIVE'")
  end


  def academic_records
    # self.student.academic_records.joins(:level).order('levels.grade desc').from_language(language_id)
    self.student.academic_records.joins({section: {course_period: [{course: :level}, :period]}}).order(['periods.year': :desc, 'periods.letter': :desc, 'levels.grade': :desc]).from_language(language_id)
  end

  def academic_record_approved
    academic_records.approved
  end

  def total_academic_hours_approved
    aux = 0
    academic_records.approved.map{|ar| aux += ar.period.academic_hours}
    return aux
  end

  def total_hours_career
    hours_period = self.last_academic_record.period.academic_hours
    total_level_language = self.language.total_levels
    hours_period.to_i*total_level_language.to_i
  end

  def finished?
    final_level = language.last_level

    last_level_approved and (final_level.eql? last_level_approved.course.grade)
  end

  def last_academic_record
    self.academic_records.first
  end

  def last_level_approved #alias last_academic_record_approved
    self.last_academic_record_approved
  end

  def last_academic_record_approved
    self.academic_records.approved.first
  end

  #====== LA IDEA ES QUE NO SE LE OFERTE PARA PREINSCRIBIR UN CURSO QUE YA TIENE PREINSCRITO O APROBADO ======#
  def last_course_enrollment
    aux = academic_records.preinscrito.last
    return aux ? aux.course : nil
  end

  def next_course_available
    course = self.language.first_course
    approved = self.last_academic_record_approved
    msg = ""
    if approved
      distance = Period.distance_between_active_enrollment_period approved.period
      
      if distance
        if (distance.eql? 0 or distance.eql? 1 or distance.eql? 2)
          course = approved.course.next_course 
        elsif (distance.eql? 3)
          course = approved.course 
          msg = "Usted a pasado 2 períodos sin aprobar su curso. Deberá tomar nuevamente su último nivel aprobado #{course.name}"
        elsif (distance > 3)
          msg = 'Usted a pasado más de 2 períodos sin aprobar un curso. Debe tomar la prueba de nivelación o comenzar  desde el primer nivel'
        end
      end
    elsif last_record = self.academic_records.last
      distance = Period.distance_between_active_enrollment_period last_record.period
      if distance and distance < 3
        course = last_record.course 
      else
        msg = 'Usted a pasado más de 2 períodos sin aprobar un curso. Debe tomar la prueba de nivelación o comenzar desde el primer nivel'
      end
    end
    [course, msg]
  end
  #=================================================================#

  def before_import_save(record)
    if (email = record[:user_email]) && (user_aux = User.find_by_email(email))
      self.student_id = user_aux.id
    end
    self.language_id = record[:language_id]
    self.agreement_id = record[:agreement_id]
  end

  def name
  	aux = ""
  	aux += "#{student.user.name}" if student and student.user
  	aux += " - #{language.name}" if language
  	aux += " - #{agreement.name}" if agreement
  	return aux
  end

end

app/controllers/careers_controller.rb
class CareersController < ApplicationController
	before_action :set_carrer#, only: [:constance, :constance_verify]
	before_action :authenticate_user!, except: [:constance_verify, :career_finished_certificate_verify]

	layout 'pdf'

	def constance
		pdf = PdfDocs.constance(@career)
		unless send_data pdf.render, filename: "constancia#{@career.student.ci.to_s}-#{@career.language_id}.pdf", type: "application/pdf", disposition: "inline"
			flash[:error] = "En estos momentos no se pueden descargar el acta, intentelo más tarde."
		end
		return
	end

	def constance_verify
	end

	def career_finished_certificate_verify
		
		if @career.finished?
			pdf = PdfDocs.career_finished_certificate(@career, true)
			unless send_data pdf.render, filename: "certificado#{@career.student.ci.to_s}-#{@career.language_id}.pdf", type: "application/pdf", disposition: "inline"
				flash[:error] = "En estos momentos no se pueden descargar el certificado, inténtelo más tarde."
			end
			return
		else
			flash[:danger] = 'No se cumplen con los requisitos para acceder al certificado solitado'
		end
		return
	end

	def career_finished_certificate
		if @career.finished?
			pdf = PdfDocs.career_finished_certificate(@career)
			unless send_data pdf.render, filename: "certificado#{@career.student.ci.to_s}-#{@career.language_id}.pdf", type: "application/pdf", disposition: "inline"
				flash[:error] = "En estos momentos no se pueden descargar el certificado, inténtelo más tarde."
			end
			return
		else
			flash[:danger] = 'No se cumplen con los requisitos para acceder al certificado solitado'
		end
		return
	end

	private

	def set_carrer
		@career = Career.find(params[:id])
	end

end

app/views/careers/_index_to_student.html.haml
%nav
  %ul#navTabStudent.nav.nav-tabs{role: :tablist}
    - careers.each_with_index do |career, i| 
      - if (i.eql? 0)
        - active = ' active'
        - selected = true
      - else
        - active = ''
        - selected = false
      
      %li= link_to career.language.name, "#tabContent#{career.language_id}", "data-toggle": :tab, class: "nav-item nav-link #{active}", role: :tab, 'aria-controls': "tabContent#{career.language_id}", id: "tab#{career.language_id}", "aria-selected": selected

#navTabStudentContent.tab-content
  - careers.each_with_index do |career, i| 
    - active = (i.eql? 0) ? ' active show' : ''

    .tab-pane.fade{id: "tabContent#{career.language_id}", class: active, "aria-labelledby": "tab#{career.language_id}", role: "tabpanel"}
      .p-3.bg-white.border.border-top-0
        = label_leveling career.leveling_period.name if career.leveling_period
            
        - if career.academic_records.approved.any?
          = link_to constance_career_path(career), class: 'btn btn-outline-primary tooltip-btn', 'data-toggle': :tooltip, title: 'Constancia de notas aprobadas' do
            .fa.fa-certificate
            Constancia

        - if career.finished?
          .align-items-center.justify-content-center.text-center
            = link_to career_finished_certificate_career_path(career), class: 'tooltip-btn btn btn-lg', 'data-toggle': :tooltip, title: "Certifiado de culminación de Curso de #{career.language.name.upcase}", style: '    background-color: darkgoldenrod;border-color: yellow;color: yellow;'  do
              .fa.fa-graduation-cap
              Certificado
              .fa.fa-certificate

        = render partial: "/student_session/enrollment_to_level", locals: {career: career} if controller_name.eql? 'student_session'
        = render partial: '/academic_records/index_to_student', locals: {records: career.academic_records}

app/views/careers/constance_verify.html.haml
.text-center

  %p.mt-3= image_tag "banner_logos_dark.png", style: 'width:80%'
  %p UNIVERSIDAD CENTRAL DE VENEZUELA
  %p Escuela de Idiomas Modernos
  %p FUNDEIM

  %h3 CONSTANCIA
.mx-5.px-5.mt-5
  %p.text-justify 
    Quien suscribe, 
    %b= GeneralSetup.director_value
    , Director de la Escuela de Idiomas Modernos de la Facultad de Humanidades y Educación de la Universidad Central de Venezuela, hace constar por medio de la presente que el ciudadano:

  %h5.my-5.text-center= @career.student.constance_name 
  %p.text-justify.mt-3
    Aprobó del curso 
    %b= @career.language.name
    los niveles que se indican a continuación:

  - t = Time.new
  %table.table.table-sm.table-hover.table-condensed.table-responsive-md.m-2
    %thead
      %tr
        %th Nivel
        %th Período
        %th Calificación
    %tbody
      - @career.academic_records.each do |ar| 
        %tr
          %td= ar.level.name
          %td= ar.period.name
          %td= ar.final_qualification

  %br
  %br
  %p.text-justify.mt-3= "Cada nivel tiene una duración de #{@career.academic_records.last.period.academic_hours} horas académicas (9 semanas aproximadamente)."
  %br
  %p.text-justify.mt-3 
    Para mayor información puede escribirnos al correo:

    %b= GeneralSetup.fundeim_email_value
    y gustosamente le atenderemos.
  %br
  %br
  %br