config/routes.rb
Rails.application.routes.draw do
  resources :billboards
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: "registrations" }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # resources :partial_qualifications

  resources :partial_qualifications
  resources :home, only: [:index, :show] do
    collection do
      # get 'select_role'
      get 'longged_in'
    end
  end

  resources :payment_details do
    member do
      get 'confirm'
      get 'read_report'
      get 'generate_pdf'
    end

  end

  resources :instructors, only: [:index] do
    member do
      get 'work_proof'
      get 'work_proof_verify'
    end
  end

  resources :careers, only: [:index] do
    member do
      get 'constance'
      get 'constance_verify'
      get 'career_finished_certificate'
      get 'career_finished_certificate_verify'
    end
  end

  resources :academic_records, only: [:index, :show] do
    member do
      get 'send_confirmation_mail'
      get 'show_payments_accounts'
      get 'certificate'
    end
  end

  resources :sections, only: [:index] do
    member do
      get 'sync_up_with_canvas'
      get 'delete'
      get 'unsplit'
      get 'split'
      get 'enrollments_to_canvas'
      get 'create_on_canvas'
    end
  end

  resources :qualification_schemas, only: [:index] do
    member do
      get 'onoff_switch'
    end
  end

  resources :periods, only: [:index] do
    member do
      get :unreported
      get 'onoff_switch'
      get 'clean_not_reported'
    end
  end

  scope module: :admin do
    resources :dashboard, only: [:index]
  end

  namespace :api do
    namespace :v1 do
      resources :items, only: [:index, :create, :destroy, :update] do 
        collection do
          get 'open_newers_registration'
        end
      end
    end
  end

  resources :student_session, only: [:index] do
    collection do
      get 'multimedia'
    end
  end
  resources :instructor_session, only: [:index] do
    member do
      get 'show_sections'
    end
  end
  resources :enrollment, only: [:index] do
    member do
      get 'regular'
      get 'import_aceim_old'
      get 'sync_up_with_canvas'
    end
  end

  resources :canvas, only: [:index] do
    member do
      get 'sync_with_canvas'
    end
  end

  resources :users, only: [:update] do
    member do
      post 'update_canvas_email'
      get 'registration_canvas'
    end
    collection do
      get 'registration_canvas_all'
    end
  end

  
  root to: 'home#index'
end

app/models/user.rb
class User < ApplicationRecord
  #=========== PAPER TRAIL ========#
  has_paper_trail

  # ========== VARIABLES ============ #
  enum canvas_status: ['nuevo', 'no_sabe', 'registrado'] 

  # ========== RELATIONSHIPS ============ #

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # has_one :user, through: :student
  
  # belongs_to :administrator, foreign_key: :user_id
  has_one :administrator, inverse_of: :user
  # accepts_nested_attributes_for :administrator
  has_one :student, inverse_of: :user, foreign_key: :user_id
  # accepts_nested_attributes_for :student
  has_one :instructor, inverse_of: :user
  # accepts_nested_attributes_for :instructor

  has_one_attached :profile_image
  attr_accessor :remove_profile_image
  after_save { profile_image.purge if remove_profile_image.eql? '1' }  

  # ========== VALIDATIONS and CALLBACKS ============ #
  before_save :update_status_upcase_names, unless: :new_record?
  after_create :send_welcome_email
  # before_validation :upcase_names
  # validates_uniqueness_of :email#, message: 'La sección ya existe para el período seleccionado', field_name: false
  validates :email, presence: true#, uniqueness: true
  validates :name, presence: true, unless: :new_record?
  validates :last_name, presence: true, unless: :new_record?
  # validates :password, presence: true, unless: :new_record?

  # validates :number_phone, presence: true, unless: :new_record?

  attr_accessor :allow_blank_password

  # validate :acceptable_image

  # def acceptable_image
  #   unless profile_image.attached?
  #     errors.add(:foto_de_perfil, "debe ser cargarda.")
  #   end

  #   # resize_image if profile_image.blob.content_type.start_with? 'image/'

  #   # unless profile_image.byte_size <= 5.megabyte
  #   #   errors.add(:profile_image, "Archivo muy grande, por favor reduzca el tamaño de la imagen e inténtelo de nuevo")
  #   # end

  # end

  def resize_image
    # resized_image = MiniMagick::Image.read(backup_file)
    resized_image = MiniMagick::Image.new(self.backup_file, '400x300^')

    # resized_image.resize('400x300^')
    v_filename = backup_file.filename
    v_content_type = backup_file.content_type
    backup_file.purge
    backup_file.attach(io: File.open(resized_image.path), filename:  v_filename, content_type: v_content_type)
  end



  # ========== SCOPE ============ #


  # ========== DEVISE ============ #
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable

  # ========== RAILS ADMIN ============ #

  rails_admin do

    # import do
    #   mapping_key :email
    #   # for multiple values, use mapping_key [:first_name, :last_name]
    #   mapping_key_list [:email, :name, :last_name, :number_phone]
    #   # field :email
    #   # field :name
    #   # field :last_name
    #   # field :number_phone
    #   # field :password
    # end

    export do
      field :email
      field :name do
        label 'Nombres'
      end
      field :last_name do
        label 'Apellidos'
      end
      field :number_phone do
        label 'Teléfono'
      end
      field :id_canvas
      field :canvas_email
    end

    list do
      checkboxes false
      sort_by :name
      field :last_name do
        label 'Apellidos'
      end
      field :name do
        label 'Nombre'
      end
      field :email do
        label 'Correo'
      end
      field :number_phone do
        label 'Número Telefónico'
      end
      field :administrator do
        label 'Administrador'
      end
      field :student do
        label 'Estudiante'
      end
      field :instructor do
        label 'Instructor'
      end
    end
    show do
      field :description do
        label 'Descripción'
        # css_class 'bg-dark text-white'
      end

      field :number_phone_style do
        label 'Número Telefónico'
        # css_class 'bg-dark text-white'
      end
      
      field :types_users do
        label 'Tipos de usuario'

      end
    end

    edit do

      field :profile_image, :active_storage do
        label 'Adjunto'
        delete_method :remove_profile_image
      end

      field :name do
        label 'Nombres'
      end
      field :last_name do
        label 'Apellidos'
      end
      field :email do
        label 'Correo'
      end
      field :canvas_email do
        label 'Correo de Canvas'
      end

      field :login_id_canvas do
        label 'Login Id Canvas'
      end

      field :id_canvas do
        label 'Id Canvas'
      end

      field :canvas_status do
        label 'Status Canvas'
      end


      field :number_phone do
        label 'Número Telefónico'
        html_attributes do
          {:length => 12, :size => 12, :onInput => "$(this).val($(this).val().toUpperCase().replace(/[^0-9]/g,''))"}
        end        
      end

      field :password do
        label 'Contraseña'
      end
      field :password_confirmation do
        label 'Confirmar Contraseña'
      end
    end
  end

  # ========== FUNCTIONS ============ #
  def label_canvas_status
    value = ''
    if self.registrado? 
      aux = 'danger' 
      icon = 'fa-copyright'
      value = 'Registrado'
    elsif self.no_sabe?
      aux = 'warning'
      icon = 'fa-chain-broken' # #fa-pied-piper-alt
    else
      aux = 'default'
      icon = 'fa-toggle-on'
    end
    i = "<i class='fa #{icon}'></i>"
    "<span class='label label-#{aux} tooltip-btn' data-toggle= 'tooltip', data-original-title= '#{self.canvas_status.titleize}'>#{i} #{value}</span>".html_safe


  end


  def name_for_email_canvas
    aux = canvas_email
    aux ||= email

    "#{name} #{last_name} <#{aux}>"
  end

  def number_phone_style
    number_phone ? self.split_phone.join(" - ") : ""
  end

  def types_users
    aux = []
    aux << 'Administrator' if administrator?
    aux << 'Estudiante' if student?
    aux << 'Instructor' if instructor?

    aux.to_sentence
  end

  def instructor?
    self.instructor ? true : false
  end

  def admin?
    administrator?    
  end

  def administrator?
    self.administrator ? true : false
  end

  def student?
    self.student ? true : false
  end

  def any_blank?
    (name.blank? or last_name.blank? or (profile_image.nil? or (profile_image and !profile_image.attached?)) or (number_phone.nil? or (number_phone and number_phone.length < 10))) ? true : false
  end

  def full_name
    "#{name} #{last_name}"
  end

  def full_name_invert
    "#{last_name}, #{name}"
  end

  def description
    "#{full_name_invert} (#{email})"
  end

  def description_with_profile

    aux = description
    aux =+ "#{image_tag(main_app.url_for(profile_image(:thumbnail)))}".html_safe if profile_image and profile_image.attached?
  end

  def password_required?
    allow_blank_password ? false : super
  end

  def before_import_save(record)
    self.password = record[:password] #"aceim123"
    # @password = record[:password]
    p "Estamos Acá en before_import_save, record[password]: #{record[:password]}"
    # self.encrypted_password = password_digest(@password) if @password.present?
    # self.allow_blank_password = true
  end

  def update_status_upcase_names
    self.name = capitalize_by_word(self.name)
    self.last_name = capitalize_by_word(self.last_name) 
    self.canvas_status = :registrado if (self.id_canvas or !self.canvas_email.blank?)
  end

  def capitalize_by_word(string)
    string.blank? ? '' : string.split.map{|w| w.capitalize}.join(" ")
  end

  def split_phone
    operator_code = self.number_phone[0..3] 
    complement = self.number_phone[3..10]
    return [operator_code, complement]
  end

  def any_rol?
    (self.how_many_roles? > 0)
  end

  def without_rol?
    (self.how_many_roles? == 0)
  end

  def how_many_roles?
    aux = 0
    aux += 1 if administrator?
    aux += 1 if student?
    aux += 1 if instructor?    
    return aux
  end
  # def before_import_attributes(record)
  #   p 'Estamos Acá en before_import_attributes'
  #   # self.encrypted_password = password_digest(@password) if @password.present?
  # end

  # def before_import_associations(record)
  #   # @password = record[:password]
  #   p 'Estamos Acá en before_import_associations'
  #   # self.encrypted_password = password_digest(@password) if @password.present?
  #   # record.delete(:password)
  # end
  private

  def send_welcome_email
    UserMailer.welcome_email(self).deliver_later
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, except: [:index, :new, :create, :registration_canvas_all]
	before_action :authenticate_user!, except: [:update]
	before_action :setup_data, only: :update

	def registration_canvas_all
		period = Period.find params[:period_id]
		total = 0
		period.academic_records.confirmado.not_canvas_registers.each do |ar|
			total += 1 if ar.user.update(canvas_email: ar.user.email) and UserMailer.canvas_registration(ar.user).deliver_later
		end
		flash[:info] = "Se envirán #{total} correos y el mismo número de usuarios han sido actualizados."
		redirect_back fallback_location: '/admin/academic_record'
	end

	def registration_canvas
		status = @user.canvas_status
		if @user.update(canvas_email: @user.email)
			aux = 'Usuario Registrado en Canvas.'
			aux += ' Correo enviado al usuario.' if UserMailer.canvas_registration(@user).deliver_later
			flash[:success] = aux
		else
			flash[:danger] = 'Un error ha ocurrido intentando actualizar los datos del usuario, por favor verifique estos e inténtelo nuevamente.'
		end
		redirect_back fallback_location: '/admin/academic_record'
	end

	def update_canvas_email

		if @user.update(user_params)
			flash[:success] = "Email de Canvas actualizado con éxito"
		else
			flash[:danger] = "Error: #{@user.errors.full_messages.to_sentence}"
		end
		redirect_to student_session_index_path
	end
	def update
		# AVANCES EN EL AUTOREGISTRO EN CANVAS Y LA CONEXIÓN CON LA API
		# require 'canvas-api'
		# canvas = MyCanvas.connect

		# # main_account = canvas.get("/api/v1/accounts/#{ENV['CANVAS_ACCOUNT_ID']}/users")
		# main_account = canvas.get("/api/v1/sis_account_id/sis_account_id:self/users")

		# main_account = canvas.post("/api/v1/accounts/self/users", {user: {name: @user.full_name, short_name: @user.name, sortable_name: @user.last_name, terms_of_use: true}, pseudonym: {unique_id: @user.email, password: user_params[:password]}})
		# flash[:canvas] = main_account
		# user_canvas = canvas.post("/api/v1/accounts/#{ENV['CANVAS_ACCOUNT_ID']}/self_registration", {user: {name: @user.full_name, short_name: @user.name, sortable_name: @user.last_name, terms_of_use: true}, pseudonym: {unique_id: @user.email, password: user_params[:password]}})




		if @user.update(user_params)
				
			if student = @user.student and student_params
				if student.update(student_params)
					flash[:success] = "Datos del estudiante actualizados con éxito."
				else
					flash[:error] = student.errors.full_messages.to_sentence
				end
			elsif instructor = @user.instructor and instructor_params
				ba = instructor.bank_account				
				ba = BankAccount.new if ba.nil?

				ba.number = params[:bank_account][:number]
				ba.holder = "#{instructor.ci}-#{params[:bank_account][:number]}"
				ba.bank_id = params[:bank_account][:bank_id]
				ba.account_type = params[:bank_account][:account_type]
				if ba.save

					flash[:success] = "Datos de la cuenta actualizados con éxito."
					instructor.bank_account = ba
					if instructor.update(instructor_params)
						flash[:success] = "Datos del instructor actualizados con éxito."
					else
						flash[:error] = instructor.errors.full_messages.to_sentence
					end

				else
					flash[:error] = ba.errors.full_messages.to_sentence
				end
			end
		else
			flash[:error] = @user.errors.full_messages.to_sentence
		end
		redirect_back fallback_location: student_session_index_path
	end

	private
      # Use callbacks to share common setup or constraints between actions.
	def set_user
		@user = User.find(params[:id])
	end

	def setup_data
		params[:user][:number_phone] = "#{params[:operator_code]}#{params[:user][:number_phone]}" if (params[:user][:number_phone] and params[:operator_code])
		aux = params[:user][:sign_in_count].to_i
		params[:user][:sign_in_count] = aux+1 if (aux.eql? 0)
		params[:student][:source_country] = "Venezuela" if params[:student]
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def student_params
		params.require(:student).permit(:personal_identity_document, :location, :source_country) if params[:student]
	end

	def instructor_params
		params.require(:instructor).permit(:ci, :rif) if params[:instructor]
	end

	def user_params
		params.require(:user).permit(:name, :last_name, :email, :number_phone, :sign_in_count, :password, :password_confirmation, :canvas_email, :canvas_status, :profile_image)
	end

end

app/views/users/_canvas_email_form.html.haml
= form_tag(update_canvas_email_user_path(@user.id)) do
  .form-group
    = label_tag 'user[canvas_email]', 'Correo de Canvas:'
    = email_field_tag 'user[canvas_email]', @user.email, autofocus: true, placeholder: 'Correo Canvas', class: 'form-control', required: true
    .text-muted * Solo modifíquelo si no es el mismo que usa para ingresar a esa plataforma

  %button.btn.btn-primary.btn-lg.btn-block{:type => "submit"} Guardar

app/views/users/_canvas_status.html.haml
= ar.user.label_canvas_status
- if ar.user.nuevo? or ar.user.no_sabe?
	= link_to "/users/#{ar.user.id}/registration_canvas", class: 'label label-success tooltip-btn', 'data-toggle': :tolltip, title: 'Registrar y enviar correo', 'data-confirm': 'Está acción asignará al IdCanvas del usuario el correo principal del mismo. Adicionalmente, le enviará el correo de Registro en Canvas. ¿Está seguro?', style: '    margin-left: 4px;' do
		%i.fa.fa-gavel
		%i.fa.fa-envelope
		%i.fa.fa-mail-forward

app/views/users/_form.html.haml
=# "VALOR DE CONTADOR DE SESSIONES: #{current_user.sign_in_count}"
= form_for @user do |f|

  -if @user.profile_image.nil? or (@user.profile_image and !@user.profile_image.attached?)

    .mb-3
      = label_tag 'user[profile_image]', 'Foto de Perfil:'
      = f.file_field :profile_image, class: 'form-control', accept: "image/jpeg,image/jpg,image/png", required: true
      .text-muted Debe agregar una fotografía de frente, dónde se vea su rostro para su perfil de usuario.
  - if @user and @user.instructor and session[:instructor]
    =# IMPORTANTE: Colocamos session[:student] para contemplar los casos de multiples roles 
    %h5.text-primary Datos Personales y de Contactos
    
    .form-group
      .row
        .col-6
          = label_tag 'instructor[ci]', 'Cédula de Identidad:'
          = text_field_tag 'instructor[ci]', @user.instructor.ci, placeholder: 'Documento de Identidad', class: 'form-control upcase', onInput: "onlyNumber(this);maxSize(this, 9)", required: true
        .col-6
          = label_tag 'instructor[rif]', 'Rif:'
          = text_field_tag 'instructor[rif]', @user.instructor.rif, placeholder: 'Registro de identificación Fiscal Rif', class: 'form-control', required: true
  - if @user and @user.student and session[:student]
    =# IMPORTANTE: Colocamos session[:student] para contemplar los casos de multiples roles 

    .form-group
      .row
        .col-6
          = f.label :number_phone, value: 'Número Documento de Identidad:'

          = text_field_tag 'student[personal_identity_document]', @user.student.personal_identity_document, placeholder: 'Documento de Identidad', class: 'form-control upcase', onInput: "onlyNumber(this);maxSize(this, 9)", required: true, autofocus: true
        .col-6
          = f.label :email, value: 'Correo:'
          = f.email_field :email, placeholder: 'Correo', class: 'form-control', required: true
  - else
    .form-group
      = f.label :email, value: 'Correo:'
      = f.email_field :email, autofocus: true, placeholder: 'Correo', class: 'form-control', required: true

  - if false
    .form-group
      = f.label :password, value: 'Contraseña:'
      = f.password_field :password, placeholder: 'Contraseña', class: 'form-control', required: true
    .form-group
      = f.label :confirmation_password, value: 'Confirmación de Contraseña:'
      = f.password_field :password, placeholder: 'Confirmación de Contraseña', class: 'form-control', required: true

  .form-group
    .row
      .col-6
        = f.label :number_phone, value: 'Nombres:'
        = f.text_field :name, placeholder: 'Nombres', class: 'form-control', onInput: "disnableSpecialChar(this);", required: true
      .col-6
        = f.label :number_phone, value: 'Apellidos:'
        = f.text_field :last_name, placeholder: 'Apellidos', class: 'form-control', onInput: "disnableSpecialChar(this);", required: true
  .form-group
    .row
      .col-6
        = f.label :number_phone, value: 'Número Telefónico:'
      - if @user and @user.student and session[:student]
        .col-6
          = label_tag 'Ubicación:'
    .row
      - @operators_code = ['0412', '0414', '0424', '0416','0426']
      - if (@user and @user.number_phone)
        -# @operator_code, @user.number_phone = @user.split_phone
        - if @user.number_phone.length >= 10
          - @operator_code = @user.number_phone[0..3]
          - @user.number_phone = @user.number_phone[4..10]
      .col-2 
        =# select_tag :oparator_code, options_for_select(@operators_code, @operator_code), class: 'form-control', required: true, include_blank: 'Operadora'
        = text_field_tag :operator_code, @operator_code, class: 'form-control', required: true, placeholder: '04XX', onInput: "onlyNumber(this);maxSize(this, 4)"
      .col-4
        = f.text_field :number_phone, placeholder: 'XXXXXXX', class: 'form-control upcase', onInput: "onlyNumber(this);maxSize(this, 7)", required: true
      - if @user and @user.student and session[:student]
        .col-6
          = text_field_tag 'student[location]', @user.student.location, placeholder: 'Dirección Corta', class: 'form-control upcase', required: true
  = f.hidden_field :sign_in_count
  - if @user
    = render partial: '/users/form_datos_canvas', locals: {f: f} if (@user and @user.student and session[:student])
    = render partial: '/bank_account/form', locals: {bank_account: @user.instructor.bank_account} if (@user and @user.instructor and session[:instructor])

  - if false
    .form-group
      =# label_tag 'Origen:'
      = hidden_field_tag 'student[source_country]', 'Venezuela', placeholder: 'País de Origen', disabled: true, class: 'form-control'

  %button.btn.btn-primary.btn-lg.btn-block{type: :submit, data: {'disable-with': 'Cargando imagen, por favor espere ...' }} Guardar
:javascript
  
  function canvasEmail(value){
    document.getElementById('user_canvas_email').disabled = value
  }
  
  function disnableSpecialChar(elem) {
    return elem.value = elem.value.replace(/[^A-Z|a-z| |Ñ]/g, '');
  }

  function onlyNumber(elem){
    return elem.value = elem.value.replace(/[^0-9]/g,'');
  }
  function maxSize(elem, size){
    return elem.value = elem.value.substring(0, size)
  }

app/views/users/_form_datos_canvas.html.haml
%hr
.form-group
  %h5.text-center 
    La plataforma educativa que utilizamos para las clases es 
    %b{style: 'color: red'} CANVAS
  .alert.alert-warning
    %b Por favor, indique lo siguiente:
    %br
    %br
    - canvas = "<b class='canvas'>CANVAS</b>"
    %p 
      = radio_button_tag 'user[canvas_status]', :registrado, true, onclick: "canvasEmail(false)"
      = "Si tiene usuario en #{canvas}, recuerda su contraseña y funciona bien, coloque el correo que tiene registrado en esa plataforma en la siguiente casilla.".html_safe
    = f.email_field :canvas_email, placeholder: 'Correo Canvas', class: 'form-control', required: true
    .mt-4
      %p
        = radio_button_tag 'user[canvas_status]', :nuevo, false, onclick: 'canvasEmail(true)'
        = "Si no tiene usuario en #{canvas} marque esta casilla para brindarle apoyo con la creación de su usuario en esa plataforma. Nos comunicaremos con usted cuando hayamos creado su usuario en #{canvas}.".html_safe
    .mt-4
      = radio_button_tag 'user[canvas_status]', 'no_sabe', false, onclick: 'canvasEmail(true)'
      = "Si tiene usuario en #{canvas} y no recuerda su usuario o contraseña, marque esta casilla para brindarle el apoyo correspondiente. Nos comunicaremos con usted en breve.".html_safe