config/routes.rb
Rails.application.routes.draw do
  resources :billboards
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: "registrations" }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # resources :partial_qualifications

  resources :partial_qualifications
  resources :home, only: [:index, :show] do
    collection do
      # get 'select_role'
      get 'longged_in'
    end
  end

  resources :payment_details do
    member do
      get 'confirm'
      get 'read_report'
      get 'generate_pdf'
    end

  end

  resources :instructors, only: [:index] do
    member do
      get 'work_proof'
      get 'work_proof_verify'
    end
  end

  resources :careers, only: [:index] do
    member do
      get 'constance'
      get 'constance_verify'
      get 'career_finished_certificate'
      get 'career_finished_certificate_verify'
    end
  end

  resources :academic_records, only: [:index, :show] do
    member do
      get 'send_confirmation_mail'
      get 'show_payments_accounts'
      get 'certificate'
    end
  end

  resources :sections, only: [:index] do
    member do
      get 'sync_up_with_canvas'
      get 'delete'
      get 'unsplit'
      get 'split'
      get 'enrollments_to_canvas'
      get 'create_on_canvas'
    end
  end

  resources :qualification_schemas, only: [:index] do
    member do
      get 'onoff_switch'
    end
  end

  resources :periods, only: [:index] do
    member do
      get :unreported
      get 'onoff_switch'
      get 'clean_not_reported'
    end
  end

  scope module: :admin do
    resources :dashboard, only: [:index]
  end

  namespace :api do
    namespace :v1 do
      resources :items, only: [:index, :create, :destroy, :update] do 
        collection do
          get 'open_newers_registration'
        end
      end
    end
  end

  resources :student_session, only: [:index] do
    collection do
      get 'multimedia'
    end
  end
  resources :instructor_session, only: [:index] do
    member do
      get 'show_sections'
    end
  end
  resources :enrollment, only: [:index] do
    member do
      get 'regular'
      get 'import_aceim_old'
      get 'sync_up_with_canvas'
    end
  end

  resources :canvas, only: [:index] do
    member do
      get 'sync_with_canvas'
    end
  end

  resources :users, only: [:update] do
    member do
      post 'update_canvas_email'
      get 'registration_canvas'
    end
    collection do
      get 'registration_canvas_all'
    end
  end

  
  root to: 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	skip_before_action :authenticate_user!, only: [:index,:longged_in]
	def index
		session.clear
	end

	def longged_in
		render json: user_signed_in?
	end

	def show
		@roles = params[:id]
	end
end

app/views/home/index.html.haml
= react_component "Home/MainTitle"

.text-center.align-middle
	= link_to 'Ingreso Primer Nivel', new_user_registration_path, class: 'btn btn-success btn-lg mr-3' if GeneralSetup.permitir_registros_nuevos

	= link_to 'Nuevo Ingreso Por Nivelación', new_user_registration_path, class: 'btn btn-warning btn-lg mr-3' if GeneralSetup.enable_leveling
	
	= link_to 'Ingreso Regular', user_session_path, class: 'btn btn-primary btn-lg'

	- if false
		- Billboard.enableds.order(sequence: :asc).each do |bb| 
			.m-3.p-3
				= raw bb.content

app/views/home/select_role.html.haml
%br
%br

.content.p-5
	%h2 Seleccione Rol:

	%ol 
		%li= link_to 'Administrador', rails_admin_path if current_user.administrator?
		%li= link_to 'Estudiante', student_session_index_path if current_user.student?

app/views/home/show.html.haml
%br
%br

.content.p-5
	%h2 Seleccione Rol:

	%ol
		- if current_user.administrator?
			%li= link_to 'Administrador', rails_admin_path
		- if current_user.student?
			%li= link_to 'Estudiante', student_session_index_path 
		- if current_user.instructor?
			%li= link_to 'Instructor', instructor_session_index_path