config/routes.rb
Rails.application.routes.draw do
  resources :billboards
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: "registrations" }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # resources :partial_qualifications

  resources :partial_qualifications
  resources :home, only: [:index, :show] do
    collection do
      # get 'select_role'
      get 'longged_in'
    end
  end

  resources :payment_details do
    member do
      get 'confirm'
      get 'read_report'
      get 'generate_pdf'
    end

  end

  resources :instructors, only: [:index] do
    member do
      get 'work_proof'
      get 'work_proof_verify'
    end
  end

  resources :careers, only: [:index] do
    member do
      get 'constance'
      get 'constance_verify'
      get 'career_finished_certificate'
      get 'career_finished_certificate_verify'
    end
  end

  resources :academic_records, only: [:index, :show] do
    member do
      get 'send_confirmation_mail'
      get 'show_payments_accounts'
      get 'certificate'
    end
  end

  resources :sections, only: [:index] do
    member do
      get 'sync_up_with_canvas'
      get 'delete'
      get 'unsplit'
      get 'split'
      get 'enrollments_to_canvas'
      get 'create_on_canvas'
    end
  end

  resources :qualification_schemas, only: [:index] do
    member do
      get 'onoff_switch'
    end
  end

  resources :periods, only: [:index] do
    member do
      get :unreported
      get 'onoff_switch'
      get 'clean_not_reported'
    end
  end

  scope module: :admin do
    resources :dashboard, only: [:index]
  end

  namespace :api do
    namespace :v1 do
      resources :items, only: [:index, :create, :destroy, :update] do 
        collection do
          get 'open_newers_registration'
        end
      end
    end
  end

  resources :student_session, only: [:index] do
    collection do
      get 'multimedia'
    end
  end
  resources :instructor_session, only: [:index] do
    member do
      get 'show_sections'
    end
  end
  resources :enrollment, only: [:index] do
    member do
      get 'regular'
      get 'import_aceim_old'
      get 'sync_up_with_canvas'
    end
  end

  resources :canvas, only: [:index] do
    member do
      get 'sync_with_canvas'
    end
  end

  resources :users, only: [:update] do
    member do
      post 'update_canvas_email'
      get 'registration_canvas'
    end
    collection do
      get 'registration_canvas_all'
    end
  end

  
  root to: 'home#index'
end

app/controllers/student_session_controller.rb
class StudentSessionController < ApplicationController

	before_action :authenticate_user!
	
	def index
		if params[:id]
			@user =  User.find(params[:id])
		else
			@user = current_user
		end
	end

	def regular_enrollment
		1/0
	end
end

app/views/student_session/_academic_details.html.haml
- #OJO: REEMPLAZAR POR PERIOD DE INSCRIPCION
- period = Period.where(enrollment: true).last
- student = @user.student

- if flash[:success_enrolled]
  .alert.alert-success
    %h3 ¡Haz completado el primer paso satisfactoriamente!
    %p 
      Te invitamos amablemente a estar pendiente de las publicaciones que haremos en nuestra cuenta en twitter 
      = link_to '@fundeim', 'https://twitter.com/Fundeim' 
      sobre el siguiente paso: 
      %b la automatriculación en su curso ONLINE en la plataforma CANVAS.
- ar = student.academic_records.preinscrito.reject{|ar| !ar.payment_detail.nil?}.first
.text-center.align-middle
  .alert.alert-info.mt-4 En el siguiente cuadro pueden ver la organización de las actividades semanales que cada estudiante debe completar en nuestro programa de cursos de idiomas.
  %img{alt: "image", src: "#{image_path('resumen_actividades.png')}", style: 'width:55%', class: 'pt-1 pb-3'}
  =# image_tag 'resumen_actividades.png'
- if ar

  = render partial: "/bank_account/show", locals: {ar: ar}
  
- if false #unless GeneralSetup.video_tuto_canvas_value.blank?
  .text-center.align-middle
    = link_to GeneralSetup.video_tuto_canvas_value, {type: :button, class: 'tooltip-btn btn btn-sm btn-outline-success', title: 'Video ilustrativo de ayuda para Canvas', data: {toggle: :tooltip}, target: '_blank'} do
      Video Tutorial para Canvas
      %span.fa.fa-play-circle

.text-center.align-middle.mb-3
  - if Content.published.any?
    = link_to multimedia_student_session_index_path, {type: :button, class: 'tooltip-btn btn btn-lg btn-primary', title: 'Videos ilustrativos de ayuda para Canvas', data: {toggle: :tooltip}} do
      Tutoriales de Canvas
      .fa.fa-play-circle

  - @normative = render partial: 'layouts/normative'

  = link_to 'javascript:void(0)', class: "btn btn-primary btn-lg m-2 tooltip-btn diplayModalBtn", 'data-toggle': :tooltip, title: "Normativa de los cursos y pruebas de nivalación", 'aria-disabled': true, onclick: "$('law').modal()", idModal: :law do
    Normativa
    .fa.fa-legal

  = render partial: '/layouts/modal_alert', locals: {content: @normative.html_safe, title: 'NORMATIVA DE LOS CURSOS', id: 'law', url: 'javascript:void(0)', informative: true}

-if student
  - if period and (GeneralSetup.enable_leveling or GeneralSetup.permitir_registros_nuevos)
    - @normative = "<b>Para completar la preinscripción en el NIVEL, ESTUDIANTE, CURSO, PERIODO EN LA MODALIDAD ONLINE USTED DEBE LEER, ACEPTAR Y ESTAR DE ACUERDO CON LA SIGUIENTE NORMATIVA:</b></br></br>"

    - @normative += render partial: 'layouts/normative'
    
    - @normative += "<p>¡Mucho éxito en sus clases!</p>"

    - @normative += "<b id='titleConfirmation'></b>"

    = render partial: '/layouts/modal_alert', locals: {content: @normative.html_safe, title: '¡IMPORTANTE!', id: 'confirmDialog', url: nil, informative: false}

    - if GeneralSetup.enable_leveling
      = render partial: "/student_session/availables_language_leveling", locals: {student: student, period: period}
    - if GeneralSetup.permitir_registros_nuevos
      = render partial: "/student_session/enrollment_language_availables", locals: {student: student, period: period}
  
  .container-fluid.middle-box.text-center.animated.fadeInDown
    = render partial: '/careers/index_to_student', locals: {careers: student.careers}

app/views/student_session/_academic_records.html.haml
- #OJO: REEMPLAZAR POR PERIOD DE INSCRIPCION
- period = Period.where(enrollment: true).last
%h5.p-2.my-5.bg-dark.text-white.text-center= "Dashboard - #{@user.description}"
- student = @user.student

- if flash[:success_enrolled]
  .alert.alert-success
    %h3 ¡Haz completado el primer paso satisfactoriamente!
    %p 
      Te invitamos amablemente a estar pendiente de las publicaciones que haremos en nuestra cuenta en twitter 
      = link_to '@fundeim', 'https://twitter.com/Fundeim' 
      sobre el siguiente paso: 
      %b la automatriculación en su curso ONLINE en la plataforma CANVAS.
- ar = student.academic_records.preinscrito.reject{|ar| !ar.payment_detail.nil?}.first
- if ar
  = render partial: "/bank_account/show", locals: {ar: ar}

-if student
  - if GeneralSetup.permitir_registros_nuevos and period.allow_enrollments?
    .text-center
      - student.language_avaliables.each do |lan| 
        - cp = lan.first_course.course_periods.online.from_period(period.id).first
        - if cp.sections.any?
          - total_enrolls = cp.academic_records.preinscrito.count
          - availables = cp.capacity - total_enrolls
          - disabled = (availables <= 0)
          - class_disadled = disabled ? 'disabled' : ''

          - section = cp.sections.first
          = link_to "#{regular_enrollment_path(section.id)}?student_id=#{student.id}", class: "#{class_disadled} btn btn-success m-2 tooltip-btn", 'data-confirm': "¿Confirma que deseas completar la preinscripcion de '#{@user.description}' en el curso: '#{cp.description_inscription}'?", 'data-toggle': :tooltip, title: "Inscribirse en #{cp.description_inscription}", 'aria-disabled': disabled do
            = "¡Nuevo curso de #{lan.name.capitalize}!"
            = "(cupos: #{availables})"

  - student.careers.each do |career| 
    .border.p-3.m-3
      %h4
        = career.language.name 
        - approved = career.last_level_approved
        = "(#{approved.level.name} Aprobado)" if approved

        - if GeneralSetup.permitir_registros_nuevos and period.allow_enrollments? 
          - next_course = career.next_course_available
          - if next_course
            - cp = period.course_periods.online.joins(:course).where('courses.language_id = ? AND courses.level_id = ?', next_course.language_id, next_course.level_id).first
            - if cp  and !student.enrolled_course_period?(cp.id)
              - total_enrolls = cp.academic_records.preinscrito.count
              - if total_enrolls <= cp.capacity
                - section = cp.sections.first
                - if section
                  %td
                    %b= " Nivel Online Disponible: "

                    = link_to "¡Inscríbite ahora! (#{period.name})", "#{regular_enrollment_path(section.id)}?student_id=#{student.id}", class: 'btn btn-success tooltip-btn', 'data-confirm': "¿Confirma que deseas completar la preinscripcion de '#{@user.description}' en el curso: '#{cp.description_inscription}'?", 'data_toggle': :tooltip, title: "Inscribirse en #{cp.description_inscription}"

      %table.table.table-sm.table-striped.table-hover.table-responsable
        %thead
          %tr.row
            %th.col-3 Nivel
            %th.col-1 Período
            %th.col-1 Calificación
            %th.col-2 Estado
            %th.col-2 Inscripción
            %th.col-3 Opciones
        %tbody
          - records = career.academic_records 
          - records.each do |ar|
            %tr.row
              %td.col-3= "#{ar.section.course.level.name} (#{ar.section.course_period.kind})"
              %td.col-1= ar.period_desc
              %td.col-1= ar.final_desc
              %td.col-2= ar.qualification_status.name
              %td.col-2
                %span.badge.badge-info= ar.inscription_status.capitalize
              %td.col-3
                - if false # ar.confirmado?
                  = link_to certificate_academic_record_path(ar.id),{type: 'button', class: 'tooltip-btn btn btn-sm btn-success', title: 'Ver detalle Planilla de Inscripción', data: {toggle: 'tooltip'}} do
                    Planilla de Inscripción
                    %span.fa.fa-certificate
                - if ar.online? and ar.confirmado? and ar.period.name.eql? '2020-A'
                  = link_to 'https://forms.gle/htyFNhGHoT4qbcBn9', {type: 'button', class: 'tooltip-btn btn btn-sm btn-success', title: 'Por favor, responda la encuesta sobre los cursos en linea', data: {toggle: 'tooltip', placement: 'bottom'}, target: "_blank"} do
                    Encuenta
                    %span.fa.fa-external-link
                - if ar.period.enabled_autoregister_canvas_link and ar.confirmado? and ar.course_period.online? and !ar.section.url_classroom_canvas.blank?
                  = link_to ar.section.url_classroom_canvas, {type: 'button', class: 'tooltip-btn btn btn-sm btn-success btn-circle mb-3', title: 'Haz clíc aquí para automatricularte a tu curso en CANVAS', data: {toggle: 'tooltip', placement: 'bottom'}, target: "_blank"} do
                    Automatricúlarme a mi curso ONLINE
                    %span.fa.fa-external-link
                - if ar.period.enabled_login_canvas_link and ar.confirmado? and ar.course_period.online? and ar.SC?
                  - url = GeneralSetup.url_canvas_login
                  = link_to url, {type: 'button', class: 'tooltip-btn btn btn-sm btn-success btn-circle', title: 'Haz clíc aquí para entrar a tu curso en CANVAS', data: {toggle: 'tooltip', placement: 'bottom'}, target: "_blank"} do
                    Entrar a mi curso ONLINE
                    %span.fa.fa-external-link
                - if ar.period.allow_enrollments? and ar.preinscrito? and ar.SC? and ar.payment_detail.nil?
                  = link_to "#{new_payment_detail_path}?academic_record_id=#{ar.id}", class: 'btn btn-sm btn-warning' do
                    %span.fa.fa-money
                    Reportar Pago
                    %span.fa.fa-angle-right
          - if false
            - records.currents.each do |current| 
              - course_id_aux = current.course.id
              - period_aux = current.period
              - if period_aux.enrollment?
                -# period_aux = Period.where(year: '2020', letter: 'A').first
                - online_course_period = CoursePeriod.online.where(period_id: period_aux.id, course_id: course_id_aux).first
                - if online_course_period and !student.enrolled_course_period?(online_course_period.id)
                  - section = online_course_period.sections.first
                  - if section
                    %tr
                      %td
                        %b Nivel Online Disponible:
                        = online_course_period.course.level.name
                        -# if available_course_period_insc = CoursePeriod.online.where(course_id: next_course.id).first
                        -# CoursePeriod.online.where(course_id: next_course.id).each do |available_course_period_insc| 

                        = link_to "¡Inscríbite ahora! (#{period_aux.name})", "#{regular_enrollment_path(section.id)}?student_id=#{student.id}", class: 'btn btn-sm btn-primary', 'data-confirm': "¿Confirma que deseas completar la preinscripcion de '#{@user.description}' en el curso: '#{online_course_period.description_inscription}'?"
-# else
-# period = Period.where(year: 2020).last 
-# period.course_periods.each do |cp| 
-# period.course_periods.online.each do |cp| 
- #period.course_periods.joins(:course).where("courses.level_id = ?", 'BI').online.each do |cp| 
=# link_to "¡Inscríbite #{cp.language.name.capitalize} (#{cp.kind.capitalize})", regular_enrollment_path(cp.id), class: 'btn btn-sm btn-primary', 'data-confirm': "¿Confirma que deseas completar la preinscripcion de '#{@user.description}' en el curso: '#{cp.description_inscription}'?"

-# available_courses = period.course
-# cursosp.

app/views/student_session/_availables_language_leveling.html.haml
.text-center
  -# language_leveled_ids = student.careers.leveled.map{|c| c.language_id}
  - language_leveled_ids = student.careers.reject{|c| !c.enrollment_leveling.any?}.map{|c| c.language_id}
  - languages = (language_leveled_ids.count > 0) ? Language.where('id NOT IN (?)', language_leveled_ids) : Language.all
  - languages.all.each do |lan| 
    - cp = lan.courses.levelings.first.course_periods.online.from_period(period.id).first
    - if cp and cp.sections.any?
      - total_enrolls = cp.academic_records.count
      - availables = cp.capacity - total_enrolls
      - disabled = (availables <= 0)
      - class_disadled = disabled ? 'disabled' : ''
      - msg = disabled ? 'Sin cupos' : "#{availables} #{"cupo".pluralize(availables)}"
      - section = cp.sections.first

      = link_to 'javascript:void(0)', class: "#{class_disadled} btn btn-warning m-2 tooltip-btn confirmBtn", 'data-toggle': :tooltip, title: "Inscribirse para la prueba de nivelación de #{cp.language.name}", 'aria-disabled': disabled, url: "#{regular_enrollment_path(section.id)}?student_id=#{student.id}", desc_user: @user.description, desc_inscrip: "prueba de nivelación de #{cp.language.name}"  do
        = "¡Prueba Nivelación #{lan.name.capitalize}!"
        = "(#{msg})"

app/views/student_session/_enrollment_language_availables.html.haml
.text-center
  - student.language_avaliables.each do |lan| 
    - cp = lan.first_course.course_periods.online.from_period(period.id).first
    - if cp and cp.sections.any?
      - total_enrolls = cp.academic_records.count
      - availables = cp.capacity - total_enrolls
      - disabled = (availables <= 0)
      - class_disadled = disabled ? 'disabled' : ''
      - msg = disabled ? 'Sin cupos' : "#{availables} #{"cupo".pluralize(availables)}"
      - section = cp.sections.first
      = link_to 'javascript:void(0)', class: "#{class_disadled} btn btn-success m-2 tooltip-btn confirmBtn", 'data-toggle': :tooltip, title: "Inscribirse en #{cp.description_inscription}", 'aria-disabled': disabled, url: "#{regular_enrollment_path(section.id)}?student_id=#{student.id}", desc_user: @user.description, desc_inscrip: cp.description_inscription  do
        = "¡Nuevo curso de #{lan.name.capitalize}!"
        = "(#{msg})"

app/views/student_session/_enrollment_to_level.html.haml
- period = Period.where(enrollment: true).last
- student = career.student
- next_course, msg = career.next_course_available
- if next_course and (period and period.allow_enrollments? and !period.preview.enabled_qualification? and (GeneralSetup.permitir_inscripciones_regulares or (GeneralSetup.permitir_registros_nuevos and next_course.level_id.eql? 'BASI')))

  - cp = period.course_periods.online.joins(:course).where('courses.language_id = ? AND courses.level_id = ?', next_course.language_id, next_course.level_id).first
  - if cp  and !student.enrolled_course_period?(cp.id)
    - total_enrolls = cp.academic_records.preinscrito.count
    - if total_enrolls <= cp.capacity
      - section = cp.sections.first
      - if section
        = alert_msg("<b>Atención:</b> #{msg}", 'warning') unless msg.blank?
        %td
          %h6.my-3
            = " Nivel Disponible: "

            = link_to 'javascript:void(0)', class: "btn btn-success tooltip-btn confirmBtn", 'data-toggle': :tooltip, title: "Inscribirse en #{cp.description_inscription}", url: "#{regular_enrollment_path(section.id)}?student_id=#{student.id}", desc_user: @user.description, desc_inscrip: cp.description_inscription do
              = "¡Inscribirse ahora! (#{period.name})"

app/views/student_session/index.html.haml
- if @user.student.payment_details and @user.student.payment_details.unread_report.any?

  - @payment_detail = @user.student.payment_details.unread_report.first
  - content = render partial: '/payment_details/message_payment_report' 
  = render partial: '/layouts/modal_alert', locals: {content: content, title: '¡Atención!', id: "AlertPaymentUnread", url: read_report_payment_detail_path(@payment_detail.id), informative: false}

- if @user.id.eql? current_user.id and (@user.any_blank? or @user.sign_in_count.eql? 0 or (@user.student and @user.student.any_blank?))

  - @user = @user
  - content = render partial: '/users/form'
  - title = "Datos Personales y de Contacto"
  - msg = "<strong>Atención</strong>: Por favor, actualice sus datos personales"
  - msg2 = "<strong>Los datos suministrados en el siguiente formulario serán usados para tu cuenta de Canvas</strong>"
  - id = "updatePersonalData"
  = render partial: '/layouts/modal', locals: {content: content, id: id, msg: msg, title: title, msg2: msg2 }
%br
.mb-5= render 'academic_details'

app/views/student_session/multimedia.html.haml
%br
%h5.p-3.bg-dark.text-white
  = link_to student_session_index_path, class: 'pull-left btn btn-secondary btn-sm' do
    .fa.fa-angle-left
    Regresar
  .text-center=@title

.p-3
  %nav
    %ul#navTab.nav.nav-tabs{role: :tablist}
      - i = 0
      - Content.categories.each do |cat| 
        - if Content.published.where(category: cat[0]).any?
          - if (i.eql? 0)
            - active = ' active'
            - selected = true
          - else
            - active = ''
            - selected = false
          - i += 1
          %li= link_to cat[0].titleize, "#tabContent#{cat[0].upcase}", "data-toggle": :tab, class: "nav-item nav-link #{active}", role: :tab, 'aria-controls': "tabContent#{cat[0].upcase}", id: "tab#{cat[0].upcase}", "aria-selected": selected

  #navTabContent.tab-content
    - Content.categories.each_with_index do |cat, j|
      - contents = Content.published.where(category: cat[0])
      - if contents.any?
        - active = (j.eql? 0) ? ' active show' : ''
        .tab-pane.fade{id: "tabContent#{cat[0].upcase}", class: "p-3 bg-white border border-top-0 #{active}", "aria-labelledby": "tab#{cat[0].upcase}", role: :tabpanel}
          .card-columns
            - contents.each do |media| 
              .card.bg-light
                - if media.file.attached?
                  .text-center
                    - image = (media.file.content_type.include? "image") ? media.file : 'general_doc'
                    
                    - path = Rails.application.routes.url_helpers.rails_blob_path(media.file, only_path: true)

                    = link_to path, target: '_blank' do
                      = image_tag image, class: 'card-img-top', style: 'max-height:150px;max-width:200px'

                - elsif media.url and media.url.include? 'youtu'
                  %iframe.embed-responsive.embed-responsive-4by3{allow: "accelerometer; clipboard-write; encrypted-media; gyroscope; picture-in-picture", allowfullscreen: "", frameborder: "0", src: media.url}
                .card-body.text-center
                  %h5.card-title= media.title
                  - if media.description
                    %p.card-text= media.description
%br
%br